const stands = [
    {
      num: "1",
      street: "6323 196th St SW",
      city: "Lynnwood",
      zip: "98036",
      hours: {
        week: "4:30am - 9:00pm",
        sat: "6:00am - 9:00pm",
        sun: "6:00am - 8:00pm",
      },
    },
    {
      num: "2",
      street: "659 NW Richmond Beach RD",
      city: "Shoreline",
      zip: "98177",
      hours: {
        week: "4:45am - 7:00pm",
        sat: "5:30am - 7:00pm",
        sun: "6:00am - 6:30pm",
      },
    },
    {
      num: "3",
      street: "540 Elliott Ave W.",
      city: "Seattle",
      zip: " 98119",
      hours: {
        week: "5:00am to 6:30pm",
        sat: "6:00am to 6:00pm",
        sun: "7:00am to 6:00pm",
      },
    },
    {
      num: "4",
      street: "13279 Aurora Ave N.",
      city: "Seattle",
      zip: "98133",
      hours: {
        week: "4:45am to 8:00pm",
        sat: "6:00am to 8:00pm",
        sun: "6:30am to 7:00pm",
      },
    },
    {
      num: "5",
      street: "8762 Holman Rd. NW",
      city: "Seattle",
      zip: "98117",
      hours: {
        week: "4:45am to 8:00pm",
        sat: " 6:00am to 8:00pm",
        sun: "6:00am to 7:00pm",
      },
    },
    {
      num: "6",
      street: "14327 Issaquah-Hobart Rd. SE",
      city: "Issaquah",
      zip: "98027",
      hours: {
        week: "5:00am to 8:00pm",
        sat: "6:00am to 8:00pm",
        sun: "7:00am to 7:00pm",
      },
    },
    {
      num: "7",
      street: "19119 Bothell Way NE",
      city: "Bothell",
      zip: "98011",
      hours: {
        week: "5:00am to 7:00pm",
        sat: "6:00am to 7:00pm",
        sun: "7:00am to 6:00pm",
      },
    },
    {
      num: "8",
      street: "412 164th St SW",
      city: "Lynnwood",
      zip: "98087",
      hours: {
        week: "4:45am to 8:00pm",
        sat: "5:45am to 8:00pm",
        sun: "6:45am to 7:00pm",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
    {
      num: "",
      street: "",
      city: "",
      zip: "",
      hours: {
        week: "",
        sat: "",
        sun: "",
      },
    },
];
  
export default { stands };